version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports: 
      - 5432:5432

  serving:
    image: tensorflow/serving:2.1.0
    environment:
      - MODEL_NAME=lr
      - MODEL_BASE_PATH=/opt
    volumes:
      - /opt/models:/opt/serving_model
    ports:
      - 8501:8501
    depends_on:
      - training


  training:
    image: tensorflow-project-template:0.0.1
    network_mode: "host"
    ports:
      - 8000:8000
    depends_on:
      - db
    command: 
      - make
      - init-training
        

