version: "2.1"
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  serving:
    image: tensorflow/serving:2.1.0
    environment:
      - MODEL_NAME=tensorflow-project-demo
      - MODEL_BASE_PATH=/opt
    volumes:
      - /opt/tensorflow-project-demo:/opt/tensorflow-project-demo
    ports:
      - 8501:8501

  training:
    image: tensorflow-project-template:0.0.1
    network_mode: "host"
    ports:
      - 8000:8000
      - 6006:6006
    volumes:
      - /opt/tensorflow-project-demo:/opt/tensorflow-project-demo
    depends_on:
      db:
        condition: service_healthy
    command:
      - make
      - init-training
